### ISSUE TITLE
1.8.9 Server Crash

### ISSUE THREAD

**Issue by king05** [AlexIIL/Buildcraft_1.8_Issues#101]
Hi, 
I have made a minecraft 1.8.9 Server for my modpack and when i add RFTools the server crashes...
The mod works fine on Client side.
Here are the crash report:
http://pastebin.com/yG4s4DCW
and the fml log:
http://pastebin.com/FX2QyGKZ

I'll link RFTools and Botania in a moment. 
I hope you can help me.

Sincerly king05

Edit:
here is the Botania issue:
https://github.com/williewillus/Botania/issues/77
and here is the RFTools issue:
McJty/RFTools#433
The crash report told me to contact you three authors...

**Comment by AlexIIL** [comment]
Can you try upgrading to java 8? That seems to be the issue here.

**Comment by AEnterprise** [comment]
yup java version is the issue here, the 3 listed mods are the ones that require java 8

**Comment by king05** [comment]
i have to say it to a good friend of mine... it's his root server i'm running my server on :D 
thanks for the fast help.
Razorskills say the same at the botania issue page

**Comment by AlexIIL** [comment]
Yea, I copied his answer here so no-one else looked at this issue without looking at the others :)

**Comment by king05** [comment]
i just downloadet the server to try it on my local computer with java 8 and it works fine... thanks for the help
