### ISSUE TITLE
Client crash in combination with mod: Fluxed Solars

### ISSUE THREAD

**Issue by BBoldt** [AlexIIL/Buildcraft_1.8_Issues#102]
On the server there is a fluxed solars solar panel feeding into a Buildcraft quarry.

To reproduce: Place fluxed solars solar panel on buildcraft quarry, leave the area, and come back. Upon returning you will crash.

https://gist.github.com/f94a34b893bb4c6b110c
- forge 1715
- buildcraft-7.2.0-pre6
- fluxed solars 1.5: http://minecraft.curseforge.com/projects/fluxed-solars

https://github.com/primetoxinz/FluxedSolars/issues/7

**Comment by AlexIIL** [comment]
For whatever reason this is being caused by FluxedSolars calling `recievePower()` when the quarry's world object is null.

**Comment by Xariyl** [comment]
@BBoldt  Try with 1.8; I just tested and I did not receive any crash. I had two iron-solars attached directly to a quarry, and another using the two solars with BC Kinesis Pipes. No issues found.

**Comment by BBoldt** [comment]
@Xariyl yeah, it got fixed, which is why the issue is closed now :stuck_out_tongue:

**Comment by Xariyl** [comment]
Ah... I assumed it was closed because it wasn't a BC issue.
