### ISSUE TITLE
Storing a Null and Causing NPEs to be thrown from NBT compound

### ISSUE THREAD

**Issue by JoeSchmo2840** [AlexIIL/Buildcraft_1.8_Issues#104]
http://pastebin.com/Ls4BZeQG

**Comment by AlexIIL** [comment]
How is this related to buildcraft? Please elaborate!

**Comment by AlexIIL** [comment]
At the very least please post a complete crash log or mod list so we can find out what is causing this :)

**Comment by AEnterprise** [comment]
maybe ask the sponge guys to modify that output to list the block/TE/whatever that they are detecting that is storing the null, they are iterating so must know whatever is doing it

**Comment by JoeSchmo2840** [comment]
This exception was fired when placing either the quarry or filler blocks. Since the update to sponge I am no longer seeing the exception. But was told to send you guys this message to inform you. I myself dont know code. I dont have a crash log because the exception did not crash the server.

**Comment by AlexIIL** [comment]
Thanks for clarifying. If this comes up again feel free to re-open this and we can see if its actually a problem or not :)
