### ISSUE TITLE
First Item (Top Left) of Blueprint doesnt place & Stairs dont land

### ISSUE THREAD

**Issue by ghost** [AlexIIL/Buildcraft_1.8_Issues#105]
I have tried several blueprints in the builder and for the most part they all seem to be pretty stable with the exception of one consistent issue, what ever is in the first box or top left of the list of needed items when it places them down they just disappear, the builder believes it has placed that them and even sends them to the location they should be and counts them off but they never show up.

**Update, it also appears to have a problem with steps, they also disappear in the the ether and never show up at the intended target.

Attatched is the blueprint I have been working with
[Super Giant Castle.zip](https://github.com/AlexIIL/Buildcraft_1.8_Issues/files/110873/Super.Giant.Castle.zip)
[basic house.zip](https://github.com/AlexIIL/Buildcraft_1.8_Issues/files/110874/basic.house.zip)

**Comment by AlexIIL** [comment]
Hi, was this issue fixed in a later prerelease? I didn't get around to looking at this, so could you say why you closed it please?

**Comment by ghost** [comment]
Sorry I thought I had left my notes, I ended up finding the original maps for what I was trying to build from downloaded blueprints and made my own blueprints using the architect. The first block seemed to be bad luck on my part in that it was usually a step or stone that was in the block, when I created my own blueprint the step problem fixed, my guess is a miss labeled ID or something which I found was an issue while googling on the problem. The largest issue was calling for stone, any blueprint you download that calls for stone really means cobblestone, ill explain. On the blueprint I created the actual design had stone everywhere but when the blueprint created it identified it as cobblestone. When I took the blueprint to a new world to test I filled it with cobblestone and the builder actually lays down regular stone as it appears in the original. One final issue I did find was the design I am creating is 170x170 the builder doesnt seem to have a problem with that but when you get more than 64 blocks from the builder it bugs out and you have to remove the blueprint and drop it back in and then place 1 block of your finished items into the builder and then it will show them as being complete again. Not a huge issue and may be my fault for trying to create something so large but its manageable.
attached is a zip file of the original blue print and the new blueprint I created using the alpha. There is a considerable size difference. 
One last thing, I got around the marker restriction by modifying the config file from 64 to 264 so I could create the whole castle, is there a downfall to expanding the marker reach?
[Castle Prints.zip](https://github.com/AlexIIL/Buildcraft_1.8_Issues/files/111421/Castle.Prints.zip)
