### ISSUE TITLE
[BC .pre9][Forge .1726] Ticking Entity on gate with "High/Low Energy" triggers.

### ISSUE THREAD

**Issue by MrGraphic** [AlexIIL/Buildcraft_1.8_Issues#106]
https://gist.github.com/MrGraphic/108f38c2b296d4a6ee72

BTW @AlexIIL do you have some list with known issues ? There would be few that I can post but I see no reason if you know about them like in case of invisible refinery/robots in inventory or broken lenses.

**Comment by AlexIIL** [comment]
Thanks for the crash report- I'll take a look at it in the morning :)

The issue list is kind of a mess right now. If you can't find an issue you have found (even if it is a really obvious one) then just create an issue and I will sort out if it's a duplicate or not. That will change when BC gets out of prerelease versions, buts its probably just easier for everyone this way right now.

As for broken lenses they have been fixed for pre10, and if robots aren't too difficult to do they will also be for pre10.

**Comment by AlexIIL** [comment]
Thanks. Fixed for pre10.

**Comment by MrGraphic** [comment]
Cool. I will open as many issues as possible ;).
After pre-10 of course.

**Comment by AlexIIL** [comment]
Fixed in pre10.
