### ISSUE TITLE
[pre9] Quarry and engine issues

### ISSUE THREAD

**Issue by maqjav** [AlexIIL/Buildcraft_1.8_Issues#107]
Hello.

After playing a couple of hours without problems I went to pick up some stone from my quarry and I realized it was stopped. I looked at my engine hooked up to the quarry (combustion engine with water and lava) and it wasn't producing energy, it was on, it was full with lava and water but no energy...
I tried removing it and adding it again and now it's collecting water but no lava (the lava pipe is filled with lava and connected to a working pump).

I thought that maybe the issue was with the quarry and when I removed it an attached it again, it ignored my landmarks and created a default size quarry. I placed the landmarks again where I had them before, and the quarry in the same position but no change, same size and the worst part... the combustion engine not working.

I tried with another engine connected to the same water+lava pipes and it worked. I don't understand what's going on because I've been using that setup without problems all afternoon (and previous months with 0.10 alpha). 

The only thing that happened in the whole afternoon related to my quarry is that a creeper blew up the lava pipe while everything was working. Of course I reconstructed the pipes... and verified it was fully connected.

The worst part is that I don't see anything in the logger related to this problem.

Alex you know how my world is, the engine that isn't working is the one closest to the quarry.

Let me know how can I help.

**Comment by maqjav** [comment]
More info. I removed the second combustion engine that was working and when i placed it again (it was empty of water and lava) it started collecting water but no lava... it looks like the lava pipe got corrupted.
I tried removing the pump and adding it again with no results.

I think that when it blew up the engine producing energy connected to it got bugged and stopped working (even if it was loaded with lava), once I removed it and added it again it didn't work because it didn't have lava in it. The second engine worked because it was attached to the lava and water pipes but not producing energy (it was connected to the lasers but these weren't creating anything so there wasn't energy going on...)

The quarry ignoring the landmarks is a secondary bug I believe.

This is so weird :S

**Comment by AlexIIL** [comment]
I should have realised this before when I loaded up your world- in 1.7.10 at some point it was decided that it was too imbalanced to have lava as a fuel source. Essentially what’s happened is that the engines have loaded up with lava inside, realised they did not have a valid fuel source, and stopped.

**Comment by AlexIIL** [comment]
Which is a big issue both because you say you can't find any oil in your world and because suddenly everything needs to be reset up.

**Comment by maqjav** [comment]
Oh no...

**Comment by maqjav** [comment]
I'm going to need an updated engines tutorial xD. 
So then the combustion engine now only works with fuel?  there isn't a use for lava in BC anymore?

And what about the quarry ignoring the landmarks?

**Comment by AlexIIL** [comment]
I'm re-reading the chanelog to see why right now. As for the quarry ignoring landmarks, The quarry has to be placed next to the landmark rather than between two- however I guess you must have done that originally, so I have no idea why it ever worked :/

**Comment by maqjav** [comment]
What I did originally was to place it beside the line that connects 2 of them. Today I placed it in the same spot but nothing... I also tried to place it right beside a landmark (just in case xD), but it made a default size around the landmark. It seems it doesn't care much about landmarks anymore :3

**Comment by AlexIIL** [comment]
Huh, thats a bug then. Also BTW you can use a Stirling engine to burn lava.

**Comment by maqjav** [comment]
I will try that. I was reading the document posted by luigi in the forums, there it explains very well that you can only use oil, fuel or ethanol (added by other mods) with combustion engines.
I'm going to re-read the document. Thanks for the info about stirling engines, I didn't know you could use lava.

About the quarry let me know if I can give you more information.

Thanks.

**Comment by maqjav** [comment]
I was reading the tutorial for the last BC version and I saw that when you set 2 landmarks close to each other in the same row, they connect with a red laser (in this screenshot you can see that the laser doesn't appear). In the screenshot the distance between landmarks are 30 blocks, but I tried to put them close without getting the laser.

Blue lasers appear when one of the landmarks receive a redstone signal (this is correct).

![2016-02-01_15 44 27](https://cloud.githubusercontent.com/assets/4415709/12720603/f0235676-c8fb-11e5-9595-7d28a0aa358f.png)

In this other screenshot you can see that the quarry is properly situated (beside the "invisible red" laser that connects 2 landmarks), but you can see that the size is 9x9 (default size)

![2016-02-01_15 43 40](https://cloud.githubusercontent.com/assets/4415709/12720690/3d67528e-c8fc-11e5-83e7-1435ef9a28bf.png)

**Comment by AlexIIL** [comment]
You need to right-click one of them to make them connect (also they must be within 64 blocks of each other by default)

**Comment by maqjav** [comment]
What the... that was it! I don't think I had to do that before... once they were activated the quarry setted the yellow pipe right on top of them.

Forgive my incompetence and thanks :)
