### ISSUE TITLE
[pre-10] Facade log spam

### ISSUE THREAD

**Issue by MrGraphic** [AlexIIL/Buildcraft_1.8_Issues#108]
Every time I put a block next to facade that sits on any pipe I receive:
`[Server thread/ERROR] [BuildCraft]: TRIED TO SET THE ACTIVE STATE OF A FACEDE PLUGGABLE TO 0`
The number of lines ( same error ) depends on block type. So for stone only one,
for redstone torch it will be three, fo some modded blocks like matter receiver from rfTolls or advanced crafting table from BC it starts to spam like crazy every tick.

**Comment by AlexIIL** [comment]
Oh. That was an earlier log message from when I had no idea what a facade state was, I'll remove it for pre-10

**Comment by MrGraphic** [comment]
Cool. I will keep posting the rest small things :).

**Comment by MrGraphic** [comment]
Closing as this has been fixed in dev.
