### ISSUE TITLE
floodgate crash

### ISSUE THREAD

**Issue by JimDiGriz132** [AlexIIL/Buildcraft_1.8_Issues#110]
I was pumping lava in the floodgate and after enabling it, instead of placing the liquid in the world, the game crashed.

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
>   thaumicinfusion (ThaumicInfusion-4.77.jar)
>   ThaumcraftLoader (Thaumcraft-1.8.9-5.1.5.jar)
>   FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
>   LoadingPlugin (RandomThings-MC1.8.9-3.6.jar)
>   NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
>   LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
> Contact their authors BEFORE contacting forge
> 
> // I blame Dinnerbone.
> 
> Time: 2/4/16 9:33 PM
> Description: Ticking block entity
> 
> java.lang.NullPointerException: Ticking block entity
>   at buildcraft.factory.TileFloodGate.queueAdjacent(TileFloodGate.java:180)
>   at buildcraft.factory.TileFloodGate.rebuildQueue(TileFloodGate.java:156)
>   at buildcraft.factory.TileFloodGate.func_73660_a(TileFloodGate.java:83)
>   at net.minecraft.world.World.func_72939_s(World.java:1716)
>   at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)
>   at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
>   at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
>   at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
>   at java.lang.Thread.run(Unknown Source)
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> -- Head --
> Stacktrace:
>   at buildcraft.factory.TileFloodGate.queueAdjacent(TileFloodGate.java:180)
>   at buildcraft.factory.TileFloodGate.rebuildQueue(TileFloodGate.java:156)
>   at buildcraft.factory.TileFloodGate.func_73660_a(TileFloodGate.java:83)
> 
> -- Block entity being ticked --
> Details:
>   Name: buildcraft.factory.FloodGate // buildcraft.factory.TileFloodGate
>   Block type: ID #345 (tile.floodGateBlock // buildcraft.factory.BlockFloodGate)
>   Block data value: 0 / 0x0 / 0b0000
>   Block location: World: (177,66,32), Chunk: (at 1,4,0 in 11,2; contains blocks 176,0,32 to 191,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
>   Actual block type: ID #345 (tile.floodGateBlock // buildcraft.factory.BlockFloodGate)
>   Actual block data value: 0 / 0x0 / 0b0000
> Stacktrace:
>   at net.minecraft.world.World.func_72939_s(World.java:1716)
>   at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)
> 
> -- Affected level --
> Details:
>   Level name: worldyworld
>   All players: 1 total; [EntityPlayerMP['JimDiGriz'/3873, l='worldyworld', x=176.52, y=68.54, z=30.38]]
>   Chunk stats: ServerChunkCache: 1358 Drop: 0
>   Level seed: 97790887
>   Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
>   Level generator options: {"landScheme":"archipelago","tempScheme":"latitude","rainScheme":"small_zones","biomeSize":"small","amplitude":1.0,"generateBopOre":false}
>   Level spawn location: -166.00,64.00,228.00 - World: (-166,64,228), Chunk: (at 10,4,4 in -11,14; contains blocks -176,0,224 to -161,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
>   Level time: 2458908 game time, 1397533 day time
>   Level dimension: 0
>   Level storage version: 0x04ABD - Anvil
>   Level weather: Rain time: 134592 (now: false), thunder time: 33984 (now: false)
>   Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
> Stacktrace:
>   at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
>   at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
>   at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
>   at java.lang.Thread.run(Unknown Source)
> 
> -- System Details --
> Details:
>   Minecraft Version: 1.8.9
>   Operating System: Windows 8.1 (amd64) version 6.3
>   Java Version: 1.8.0_71, Oracle Corporation
>   Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
>   Memory: 1152479280 bytes (1099 MB) / 4216324096 bytes (4021 MB) up to 7516192768 bytes (7168 MB)
>   JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8064m
>   IntCache: cache: 0, tcache: 23, allocated: 0, tallocated: 65
>   FML: MCP 9.19 Powered by Forge 11.15.1.1729 75 mods loaded, 75 mods active
>   States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
>   UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
>   UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1729-universal.jar) 
>   UCHIJAAAA   Forge{11.15.1.1729} [Minecraft Forge](forge-1.8.9-11.15.1.1729-universal.jar) 
>   UCHIJAAAA   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
>   UCHIJAAAA   aura{unspecified} [Aura Cascade](AuraCascade-1.8.8-v0.2.2a.jar) 
>   UCHIJAAAA   bagginses{2.1.5b} [Bagginses](Bagginses-1.8.9-2.1.5b.jar) 
>   UCHIJAAAA   BetterThanBunnies{1.8.9-1.0.0} [BetterThanBunnies](BetterThanBunnies-1.8.9-1.0.0.jar) 
>   UCHIJAAAA   BiomesOPlenty{3.0.0} [Biomes O' Plenty](BiomesOPlenty-1.8.9-3.0.0.1788-universal.jar) 
>   UCHIJAAAA   BloodMagic{1.8.9-2.0.0-14} [Blood Magic: Alchemical Wizardry](BloodMagic-1.8.9-2.0.0-14.jar) 
>   UCHIJAAAA   bookshelfapi{2.2.6} [Bookshelf](Bookshelf-1.8.9-2.2.6.jar) 
>   UCHIJAAAA   Botania{r1.8-249} [Botania](Botania.r1.8-248-MC1.8-779cc76.jar) 
>   UCHIJAAAA   BuildCraft|Core{7.2.0-pre6} [BuildCraft](buildcraft-7.2.0-pre6.jar) 
>   UCHIJAAAA   BuildCraft|Transport{7.2.0-pre6} [BC Transport](buildcraft-7.2.0-pre6.jar) 
>   UCHIJAAAA   BuildCraft|Factory{7.2.0-pre6} [BC Factory](buildcraft-7.2.0-pre6.jar) 
>   UCHIJAAAA   BuildCraft|Silicon{7.2.0-pre6} [BC Silicon](buildcraft-7.2.0-pre6.jar) 
>   UCHIJAAAA   BuildCraft|Robotics{7.2.0-pre6} [BC Robotics](buildcraft-7.2.0-pre6.jar) 
>   UCHIJAAAA   BuildCraft|Energy{7.2.0-pre6} [BC Energy](buildcraft-7.2.0-pre6.jar) 
>   UCHIJAAAA   BuildCraft|Builders{7.2.0-pre6} [BC Builders](buildcraft-7.2.0-pre6.jar) 
>   UCHIJAAAA   Chameleon{1.8.9-0.2.1} [Chameleon](Chameleon-1.8.9-0.2.1.jar) 
>   UCHIJAAAA   mcmultipart{1.0.6} [MCMultiPart](MCMultiPart-1.0.6-universal.jar) 
>   UCHIJAAAA   CharsetLib{0.2.1} [‽](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
>   UCHIJAAAA   CharsetTweaks{0.2.1} [*](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
>   UCHIJAAAA   CharsetWires{0.2.1} [+](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
>   UCHIJAAAA   CharsetAudio{0.2.1} [♫](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
>   UCHIJAAAA   CharsetStorage{0.2.1} [#](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
>   UCHIJAAAA   CharsetPipes{0.2.1} [|](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
>   UCHIJAAAA   CharsetGates{0.2.1} [&](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
>   UCHIJAAAA   chisel{@VERSION@} [Chisel](Chisel-MC1.8.9-0.0.2.6.jar) 
>   UCHIJAAAA   chiselsandbits{mc1.8.9-v1.8.7} [Chisels & Bits](chiselsandbits-mc1.8.9-v1.8.7.jar) 
>   UCHIJAAAA   compasscoords{1.8.9-0.2.6} [Compass Co-ords](CompassCoords-1.8.9-0.2.6.jar) 
>   UCHIJAAAA   ComputerCraft{1.78} [ComputerCraft](ComputerCraft1.78.jar) 
>   UCHIJAAAA   crafttweaker{3.0.0} [crafttweaker](CraftTweaker-Customized-1.8.8-3.0.1.jar) 
>   UCHIJAAAA   CustomMainMenu{1.9.3} [Custom Main Menu](CustomMainMenu-MC1.8.8-1.9.3.jar) 
>   UCHIJAAAA   ShetiPhianCore{3.0.3} [ShetiPhian-Core](ShetiPhianCore-1.8.9-3.0.3.jar) 
>   UCHIJAAAA   EnderTanks{1.2.0} [EnderTanks](EnderTanks-1.8.9-1.2.0.jar) 
>   UCHIJAAAA   ezstorage{1.0} [EZ Storage](ezstorage-1.8.9-1.2.2.jar) 
>   UCHIJAAAA   fastleafdecay{1.6} [Fast Leaf Decay](FastLeafDecay-1.8-1.6.jar) 
>   UCHIJAAAA   flatcoloredblocks{mc1.8.9-v1.3} [Flat Colored Blocks](flatcoloredblocks-mc1.8.9-v1.6.jar) 
>   UCHIJAAAA   fluxedcore{2.0.2} [Fluxed-Core](Fluxed-Core-1.8.9-2.0.2.jar) 
>   UCHIJAAAA   fluxedsolars{$GRADLEVERSION} [Fluxed Solars](fluxedsolars-1.3.jar) 
>   UCHIJAAAA   Waila{1.6.0} [Waila](Waila-1.6.0-B3_1.8.8.jar) 
>   UCHIJAAAA   FTBL{2.0.2} [FTBLib](FTBLib-1.8.9-2.0.2.jar) 
>   UCHIJAAAA   FTBU{2.0.2} [FTBUtilities](FTBUtilities-1.8.9-2.0.2.jar) 
>   UCHIJAAAA   furnus{1.6} [Furnus](Furnus-1.8.9-1.6.jar) 
>   UCHIJAAAA   graves{1.8.9-b31-universal} [Graves Mod](graves-1.8.9-b31-universal.jar) 
>   UCHIJAAAA   hopperducts{1.4.6} [Hopper Ducts](hopperducts-mc1.8.8-1.4.6.jar) 
>   UCHIJAAAA   k4lib{1.8.9-1.0.11} [K4Lib](k4lib-1.8.9-1.0.11-universal.jar) 
>   UCHIJAAAA   HydCraft{1.8.9-3.1.45} [Hydraulicraft](HydCraft-1.8.9-3.1.45-universal.jar) 
>   UCHIJAAAA   IGWMod{1.2.3-3} [In-Game wiki Mod](IGW-Mod-1.8.9-1.2.3-3-universal.jar) 
>   UCHIJAAAA   inventorysorter{0.7.4+26} [Simple Inventory sorting](inventorysorter-1.8.9-0.7.4+26.jar) 
>   UCHIJAAAA   IronChest{6.0.123.769} [Iron Chest](ironchest-1.8.9-6.0.123.769.jar) 
>   UCHIJAAAA   JEI{2.24.5.128} [Just Enough Items](jei_1.8.9-2.24.5.128.jar) 
>   UCHIJAAAA   Thaumcraft{5.1.5} [Thaumcraft](Thaumcraft-1.8.9-5.1.5.jar) 
>   UCHIJAAAA   JEIAddons{0.10.1.39} [Just Enough Items Addons](JEIAddons_1.8.9-0.10.1.39.jar) 
>   UCHIJAAAA   journeymap{5.1.3} [JourneyMap](journeymap-1.8.8-5.1.3-unlimited.jar) 
>   UCHIJAAAA   jeresources{0.3.1} [Just Enough Resources](JustEnoughResources-1.8.9-0.3.1.jar) 
>   UCHIJAAAA   llor{1.0.4-mc1.8.8} [Light Level Overlay Reloaded](LLOverlayReloaded-1.0.4-mc1.8.8.jar) 
>   UCHIJAAAA   mantle{1.8.9-0.7.jenkins72} [Mantle](Mantle-1.8.9-0.7.jar) 
>   UCHIJAAAA   testdummy{1.0} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.9b.jar) 
>   UCHIJAAAA   Morpheus{1.8.9-2.0.57} [Morpheus](Morpheus-1.8.9-2.0.57.jar) 
>   UCHIJAAAA   neotech{2.3.1} [NeoTech](NeoTech-1.8.9-2.3.1.jar) 
>   UCHIJAAAA   fodc{1.7.1} [Ore Dictionary Converter](OreDictionaryConverter-1.7.1.jar) 
>   UCHIJAAAA   playerrugs{0.0.1} [Player Rugs](PlayerRugs-1.8.8-1.2.0.jar) 
>   UCHIJAAAA   PneumaticCraft{1.13.5-6} [PneumaticCraft](PneumaticCraft-1.8.9-1.13.5-6-universal.jar) 
>   UCHIJAAAA   progressiveautomation{1.6.33} [Progressive Automation](ProgressiveAutomation-1.8.9-1.6.33.jar) 
>   UCHIJAAAA   RandomThings{3.6} [Random Things](RandomThings-MC1.8.9-3.6.jar) 
>   UCHIJAAAA   redstonepaste{1.7.2} [Redstone Paste](redstonepaste-mc1.8.8-1.7.2.jar) 
>   UCHIJAAAA   ResourceLoader{1.4} [Resource Loader](ResourceLoader-MC1.8.8-1.4.jar) 
>   UCHIJAAAA   rftools{4.20beta14} [RFTools](rftools-1.8.9-4.20beta14.jar) 
>   UCHIJAAAA   simpleretrogen{2.2.2+3} [Simple Retrogen](simpleretrogen-1.8.9-2.2.2+3.jar) 
>   UCHIJAAAA   StorageDrawers{1.8.9-2.3.2} [Storage Drawers](StorageDrawers-1.8.9-2.3.2.jar) 
>   UCHIJAAAA   tanks{1.0.4} [Tanks](Tanks-1.8.9-1.0.4.jar) 
>   UCHIJAAAA   tconstruct{1.8.9-2.0.2.jenkins61} [Tinkers' Construct](TConstruct-1.8.9-2.0.2.jar) 
>   UCHIJAAAA   thaumicinfusion{4.77} [Thaumic Infusion](ThaumicInfusion-4.77.jar) 
>   UCHIJAAAA   wawla{1.4.7} [What Are We Looking At](Wawla-1.4.7-1.8+.jar) 
>   Loaded coremods (and transformers): 
> NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
>   net.fybertech.nwr.NowWithRendering
> thaumicinfusion (ThaumicInfusion-4.77.jar)
>   drunkmafia.thaumicinfusion.common.asm.BlockTransformer
>   drunkmafia.thaumicinfusion.common.asm.WorldTransformer
> ThaumcraftLoader (Thaumcraft-1.8.9-5.1.5.jar)
> 
> FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
>   com.olafski.fastleafdecay.FldTransformer
> LoadingPlugin (RandomThings-MC1.8.9-3.6.jar)
>   lumien.randomthings.asm.ClassTransformer
> NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
>   net.fybertech.nwr.NowWithRendering
> LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
>   lumien.resourceloader.asm.ClassTransformer
>   GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
>   Pulsar/tconstruct loaded Pulses: 
>       - TinkerCommons (Enabled/Forced)
>       - TinkerWorld (Enabled/Not Forced)
>       - TinkerTools (Enabled/Not Forced)
>       - TinkerSmeltery (Enabled/Not Forced)
>       - TinkerGadgets (Enabled/Not Forced)
>       - TinkerOredict (Enabled/Forced)
>       - TinkerIntegration (Enabled/Forced)
>       - TinkerFluids (Enabled/Forced)
>       - TinkerMaterials (Enabled/Forced)
>       - chiselsandbitsIntegration (Enabled/Not Forced)
>       - TinkerDebug (Enabled/Not Forced)
> 
>   Profiler Position: N/A (disabled)
>   Player Count: 1 / 8; [EntityPlayerMP['JimDiGriz'/3873, l='worldyworld', x=176.52, y=68.54, z=30.38]]
>   Type: Integrated Server (map_client.txt)
>   Is Modded: Definitely; Client brand changed to 'fml,forge

**Comment by AlexIIL** [comment]
Hi, could you try upgrading to pre-10?

**Comment by JimDiGriz132** [comment]
I'm sorry, I assumed that by using the FTB Unstable pack via Curse launcher mod would be on the latest version.. 
I just tried it again on pre-10 and it works fine. Sorry again for the false bug report!

**Comment by AlexIIL** [comment]
Thanks for clarifying :)
