### ISSUE TITLE
Stripes Transport Pipe Dupe

### ISSUE THREAD

**Issue by MoreThanHidden** [AlexIIL/Buildcraft_1.8_Issues#111]
**Running Version:**
https://github.com/BuildCraft/BuildCraft/commit/06c162bf855d1311e65e410bfadec8793fd80de8

**Issue:**
Blocks that are placed by the striped pipe aren't removed from the pipe and bounce back.

**Example:**
![animation2](https://cloud.githubusercontent.com/assets/1351964/12867106/b8e9f5e8-cd1f-11e5-8905-cc8926145f20.gif)

**Comment by AlexIIL** [comment]
Woops. I think I have found the error though.

**Comment by AlexIIL** [comment]
Should be fixed in BuildCraft/BuildCraft@d6f582915fcdecf7fddae1db1f5b30a7499e730b

**Comment by MoreThanHidden** [comment]
That did the trick, can confirm is working fine in BuildCraft/BuildCraft@d6f5829

**Comment by AlexIIL** [comment]
Thanks for checking :)
