### ISSUE TITLE
Wood/Emerald Kinesis Pipe Crash

### ISSUE THREAD

**Issue by MortisLegati** [AlexIIL/Buildcraft_1.8_Issues#114]
http://pastebin.com/G3Sbknib

Occurs whenever an RF-Producing/Pushing block is next to a kinesis pipe capable of receiving energy.
Not entirely sure whether this is related to a specific version as it occurred on world load with no significant client changes between previous load, between which block configuration didn't change.

**Comment by AlexIIL** [comment]
What mods are you using? (version numbers too please)

Also what did you change? I know that RF recently got a new API so that might be causing it, but it would mean that you changed/added a mod that shipped a different API version

**Comment by MortisLegati** [comment]
http://pastebin.com/zJKtX3Qt
There's the whole shebang.

The new API is likely the crash cause.  I think I updated a *core mod.

**Comment by AlexIIL** [comment]
Related to #113, for the moment the temp fix is to downgrade whatever mod you updated until I update to the official RF API.

**Comment by AlexIIL** [comment]
This has been fixed I think. Feel free to re-open this if I'm wrong :)
