### ISSUE TITLE
Power Pipe Issue

### ISSUE THREAD

**Issue by bubblesayoyo** [AlexIIL/Buildcraft_1.8_Issues#115]
[paste](http://pastebin.com/WLMWwuTQ)

As far as I can tell all 'RF' mods have updated to official

**Comment by AlexIIL** [comment]
That's strange... Can you reproduce this with only BC?

**Comment by bubblesayoyo** [comment]
Strange indeed, crashed when I placed the block. When I booted MC back up - worked like a charm?

**Comment by AlexIIL** [comment]
does it happen every time you place a pipe? And what block was it?

**Comment by bubblesayoyo** [comment]
Neotech solar -> wooden kinesis -> gold kinesis -> Neotech RF Storage block.

And now I cannot reproduce, it only happened the first time...

**Comment by AlexIIL** [comment]
Closing as this should be resolved by now
