### ISSUE TITLE
Connecting a Kinesis Pipe to a Filler crashes the game

### ISSUE THREAD

**Issue by 8BitLoser** [AlexIIL/Buildcraft_1.8_Issues#116]
I've tested it with golden and diamond and they both crash/corrupt the world

[Crash Log](http://pastebin.com/4inZCdRs)

I should also probably mention this is on pre10. The pre11 download says its known buggy so i havent tried it

**Comment by AEnterprise** [comment]
you'll need pre11, the crash is caused by incompatible RF api versions in your instance, pre11 uses the new official version

**Comment by 8BitLoser** [comment]
ah gotcha. Ill give it a look

**Comment by 8BitLoser** [comment]
Yep its fixed in pre11
