### ISSUE TITLE
Add items to the builder and filler by right clicking the machine

### ISSUE THREAD

**Issue by AlexIIL** [AlexIIL/Buildcraft_1.8_Issues#12]
Right clicking on the bottom front of a builder (over the empty space) would insert the blueprint or template you were holding (if it was empty).

Right clicking a builder or filler with an item in hand (say, over an item hatch in the top) would add that item to the machine.

**Comment by asiekierka** [comment]
Not sure about it, after longer thought.

**Comment by RagaRBM** [comment]
I'm not sure about this.

**Comment by AlexIIL** [comment]
I must of missed this one when I was clearing out all of the "new things" issues.

**Comment by AlexIIL** [comment]
NOT APPLICABLE
