### ISSUE TITLE
buildcraft and energy tools quarry crash

### ISSUE THREAD

**Issue by ghost** [AlexIIL/Buildcraft_1.8_Issues#120]
not sure if its a build craft crash or an energy tools one
basicly when a quarry mines a certain ore from the mod it crashes the server

crash log: http://pastebin.com/ksxEEWAh

energy tools mod : http://www.curse.com/mc-mods/minecraft/241101-energy-tools

all version numbers should be in the crash log. but any details you need please let me know, will report it to the developer of energy tools too.

**Comment by AlexIIL** [comment]
I think energy tools needs to have a range check there.

**Comment by AlexIIL** [comment]
I'm pretty sure that this has been fixed on their end.
