### ISSUE TITLE
Redstone Engine Crash

### ISSUE THREAD

**Issue by jjmcquaid** [AlexIIL/Buildcraft_1.8_Issues#121]
Game crash when activating a redstone lever placed above a redstone engine attached to a wooden transport pipe. Here's the crash report http://pastebin.com/JF86D2Jn if you need anymore info let me know.

**Comment by jjmcquaid** [comment]
It seems to happen when trying to use a wooden transport pipe to pull from a vanilla chest in any form. I've tried using different engines and gates.

**Comment by AlexIIL** [comment]
Can you update to pre-11? It looks like that is an issue with the COFH RF API.

**Comment by Xariyl** [comment]
Also make sure you're using the correct pipe. The RF API issue shouldn't be affecting the Transport pipes, to the best of my knowledge. It looks like you may have used a kinesis pipe.

But yes, definitely update to Pre-11.

**Comment by AlexIIL** [comment]
It's to do with how Java loads classes, and when you have incomparable class definitions anything is possible. So yes, the RF API issue is defiantly the cause.

**Comment by AlexIIL** [comment]
*incompatible

Damn you autocorrect.

**Comment by AlexIIL** [comment]
Also wooden transport pipes receive energy to extract items.

**Comment by Xariyl** [comment]
ah... right.

**Comment by jjmcquaid** [comment]
Updating to pre11 appears to have fixed it. I just went with pre10 cause it was the recommended download, pre11 was labeled as "buggy". But I guess they're both buggy, that's what a beta is I suppose. Thanks for the help.

**Comment by AlexIIL** [comment]
Its only buggy because I think I accidentally left some stuff I was in the middle of. It turns out that I was probably wrong, so I have removed pre10 and made pre-11 the latest.
