### ISSUE TITLE
Engine causes crash when powerd

### ISSUE THREAD

**Issue by tomownu21** [AlexIIL/Buildcraft_1.8_Issues#126]
me and some friends found a crash when we powered our quarry with a stone engine
here is the crash log
http://pastebin.com/Va3UA7Zc

sorry if this has already been fixed just thought i would pop it here

**Comment by AlexIIL** [comment]
Yes: update to pre12 (https://github.com/AlexIIL/BC-Temp-releases/releases/tag/7.2.0-pre12)
