### ISSUE TITLE
Issues Regarding Power Producers and Users

### ISSUE THREAD

**Issue by ssblur** [AlexIIL/Buildcraft_1.8_Issues#128]
There is a notable issue with Users, such as the Quarry and Builder, and Producers, such as engines, not 'placing' correctly on servers in that it seems to place the block on the server, but not relay this information to the client. This has been an issue in other mods which used RF, however it is an issue even when only Buildcraft is installed on a client and server.

This issue only occurs on servers, and is not replicable in singleplayer.

This issue is replicable with no additional mods.

This issue pertains to _at least_ the following blocks:
- Builder
- Quarry
- Stirling Engine
- Redstone Engine
- Creative Engine
- The iron one too, I forget its name.

This issue occurred in your latest public build as of the current date, pre12.

Forge is not set up to remove erroring tile entities.

No relevant errors were produced.

If I happen upon any more information, or you need any additional information, I would be more than happy to provide it.

**Comment by AlexIIL** [comment]
I cannot replicate this atm, however that mey be because I fixed this a while ago in my development environment- so this MIGHT be fixed in the next pre-release

**Comment by ssblur** [comment]
Well if it is, then I thank you, both for resolving it, and for addressing this so promptly!

If the issue is present in the next release, I will re-open this issue.

**Comment by ssblur** [comment]
Actually, it seems it may be related to the world I did this in more than anything, tried with a new world and the issue was gone.

**Comment by AlexIIL** [comment]
It does? I'm glad its not global, but I'm interested in what might be causing this.

**Comment by ssblur** [comment]
Basically, the way ID's are handled by forge in 1.8.9, numerical ID's are assigned to each text ID. Whenever items and blocks are removed, it apparently cached ID's that are no longer in the world get put into a list titled 'dummies' in the players.dat. For some reason, IDs 461 through 496 were in this 'dummies' list as well as being used by mods I added after removing the mods which now occupied those slots. My guess is that it actually read that list for some reason, and when it attempted to send the BlockState for these blocks (which were coincidentally RF using blocks), it screwed up somehow.

I would have to investigate further to determine the specific cause, but flushing this 'dummies' list resolved the issue for all involved mods.
