### ISSUE TITLE
[7.2.0-pre12] Pipes invisible on Server.

### ISSUE THREAD

**Issue by Xiaminou** [AlexIIL/Buildcraft_1.8_Issues#130]
Buildcraft pipes and anything attached to them are invisible on my server.

modlist: http://pastebin.com/HM930Lt8

**Comment by AlexIIL** [comment]
What dimension are you in? Is it only BC pipes, or are other BC machines/blocks invisible as well? Can you replicate with only buildcraft?

**Comment by Xiaminou** [comment]
I cannot reproduce with only Buildcraft. Now that you mention it the assembly table is also invisible, I haven't tested robots as I have no idea how they work. Most of the machines are fine.

**Comment by AlexIIL** [comment]
I was wondering if anything was not invisible. The assembly table being invisible is very strange as it only has a missing model, which probably means something is doing strange things to the models.

**Comment by Xiaminou** [comment]
Actually I should mention that they're not just invisible, but they're "intangible" I suppose is the correct term. I can't interact with them, can't detect them with waila, they're effectively ghost blocks.
And here is how they appear on singleplayer.
![2016-03-09_15 16 49](https://cloud.githubusercontent.com/assets/8670392/13637897/061bc06e-e60a-11e5-88e1-b41948350b5a.png)

Another side note, I used to have my world in singleplayer before pre12 (back in pre8 I think) and they used to be visible, but they'd just randomly disappear from time to time.

**Comment by AlexIIL** [comment]
So you can't right-click a machine to open its GUI? Can you make a simple chest->wooden pipe(+RS engine + RS torch)->stone pipe->chest and see if they still pull items from the first chest to the second?

It might be difficult to set up but I'm just wondering if its a rendering/networking issue or actual block issues.

Also, are you in any other dimensions? An issue was found recently that made some blocks invisible in dimensions other than the overworld (#129)

**Comment by Xiaminou** [comment]
Yeah I forgot to answer that, no it's overworld.

**Comment by Xiaminou** [comment]
Okay I'm starting to find out that everything turned invisible, even thought pumps/quarry worked not so long ago. I tried the extract/transfer of items, doesn't seem to work but it's hard to confirm since everything is invisible.

EDIT: apparently I had an assembly table adjacent to the wood pipe, removed it and now it does transfer items from one chest to another.

**Comment by AlexIIL** [comment]
Can I have a look at your fml-client-latest.log file to see if there are any oddities in it? The only other thing to try is removing all mods except BC (starting a new world) and adding them one at a time until it starts to bug out, just so we know what mod (or mods) are responsible.

**Comment by Xiaminou** [comment]
log: https://drive.google.com/file/d/0B090g8mHJkCWOGdvWGVXaDJ1RVE/view?usp=sharing

**Comment by AlexIIL** [comment]
thanks

**Comment by AlexIIL** [comment]
Nothing seems to be inherently wrong in the log file...

**Comment by Xiaminou** [comment]
Any advice on which mods would be more likely to cause that problem? so I save some time.

**Comment by Xiaminou** [comment]
Okay, so I fixed singleplayer missing textures by regenerating the config folder of buildcraft.
Deleted it on the server too but that didn't fix invisible everything, so I tried making a new world and in that new world everything is as it should be.
I then deleted the buildcraft folder inside my old world, but that didn't fix the invisibles.
I'm out of ideas, it seems to be something in the world, but what?

**Comment by Xariyl** [comment]
What happens if you disable your resource pack?
It shouldn't make a difference, I don't think Faithful includes mod textures, but looks like you've tested everything else.

Next test I would do would be to start a clean world with just BC, and start adding mods until it fails again.

**Comment by Xiaminou** [comment]
That's the first thing I tried, no difference what so ever.
as I stated previously starting a new world fixes the problem even with all the mods. So I can't determine which one, if any, causes the problem that way.
I could backup my world and start removing the mods, but I'm not sure it'll work.
I'll still give it a try.

**Comment by Xiaminou** [comment]
It's fixed, somehow, logged in today and I could see everything.
I guess it will remain a mystery.
