### ISSUE TITLE
I have the wrong forge/buildcraft version

### ISSUE THREAD

**Issue by SPACEVLC** [AlexIIL/Buildcraft_1.8_Issues#131]
I CANT INSTALL BUILD CRAFT FOR 1.8
![no 1](https://cloud.githubusercontent.com/assets/17621082/13643260/9f21bb10-e628-11e5-8490-e3764fc2fb9d.PNG)

**Comment by AlexIIL** [comment]
Hello, can you tell me what version of BuildCraft you are trying to install?

**Comment by AlexIIL** [comment]
(That means that you need to download and install a later version of MinecraftForge from http://files.minecraftforge.net)
You want the latest 1.8.9 version of forge (1.8.9 - 11.15.1.1764) and click on the installer link.

In case you haven't got bc pre12 you should also download it from [here](https://github.com/AlexIIL/BC-Temp-releases/releases/tag/7.2.0-pre12)

**Comment by AlexIIL** [comment]
I'm closing this as I'm assuming that was helpful. Feel free to reopen if it didn't, or my instructions weren’t clear.
