### ISSUE TITLE
Missing localization strings

### ISSUE THREAD

**Issue by maqjav** [AlexIIL/Buildcraft_1.8_Issues#133]
There are some strings which aren't present in the lang files so they cannot be translated properly.

For example:

Configuration:
Experimental tab:
- kinesisCanExplode
- kinesisLossMode
- kinesisPowerLossOnTravel

General tab:
- builderMaxIterationsPerItemFactor
- fuel.lava.combustion (didn't this one disappear?)
- fuel.lava.combustion.energyOutput. (didn't this one disappear?)

Etc.

I was updating the spanish localization file and I also realized that not all the strings are extracted to the properties files, so for example the toolTips of every configuration options appear in english (and they aren't in the en_US.lang file, so probably they are in the code?).

Thanks!

**Comment by AlexIIL** [comment]
What version is this for?

**Comment by AlexIIL** [comment]
Also this repo shouldn't be used for 1.8.9 issues.

Config options are not localized so that they can be shared around. Also there are no localizations on the server.

**Comment by maqjav** [comment]
BC 7.2.5

Ops, my bad, I guess is this one then https://github.com/BuildCraft/BuildCraft/issues?

Thanks

**Comment by AlexIIL** [comment]
Yes it is
