### ISSUE TITLE
https://github.com/AlexIIL/BuildCraft/commit/e04eeb4dc53f17d267ec7de60f063d1ae88d656d

### ISSUE THREAD

**Issue by loordgek** [AlexIIL/Buildcraft_1.8_Issues#28]
http://blog.jetbrains.com/idea/2014/01/intellij-idea-13-importing-code-formatter-settings-from-eclipse/
will this help you??

**Comment by AlexIIL** [comment]
Maybe. Unfortunately I'm not at my dev environment now, so I can't test it properly- import the code into idea, import my formatter and reformat the code with IDEA. Ideally I wouldn't change a single line (or I could mess around with the formatting in idea and enclose would agree on what it formats to).
