### ISSUE TITLE
Add wrench API methods for handling entities

### ISSUE THREAD

**Issue by asiekierka** [AlexIIL/Buildcraft_1.8_Issues#33]
and fix the Robot checks for ItemWrench to use IToolWrench checks

**Comment by AlexIIL** [comment]
Added in AlexIIL#BuildCraft@6f9839bf7052a1d6d5a684285db7dac76428ca6d and this is the current API (javadoc being done)

```
boolean canWrench(EntityPlayer player, Entity entity);

void wrenchUsed(EntityPlayer player, Entity entity);
```

**Comment by AlexIIL** [comment]
...And closing this as it was implemented properly ages ago
