### ISSUE TITLE
Create an in-game guide

### ISSUE THREAD

**Issue by AlexIIL** [AlexIIL/Buildcraft_1.8_Issues#34]
Like a book. This should also use the same source as the official wiki (or the guide and wiki both derive from the same repo so we only have to update one to get the wiki and the guide updated. Versioning would be nice too (so, select a Buildcraft version in the menu for the wiki). Also make change logs books. And collectables too (insertable to the main guide, which should keep track of how many versions you have played with, and show changes directly in the wiki)

**Comment by asiekierka** [comment]
See buildcraft.core.tablet

**Comment by AlexIIL** [comment]
I missed that one... Does it do anything right now though? Or is it just a display with client-server waiting for a guide implementation?

**Comment by asiekierka** [comment]
> Or is it just a display with client-server waiting for a guide implementation?

It's that, yes. But it might be killed off in the future.

**Comment by AlexIIL** [comment]
No longer an issue/going on my private BC neptune plan document

**Comment by asiekierka** [comment]
Private plan documents? Aww. Make it public like my BC8 document! :P

2015-12-20 16:35 GMT+01:00 AlexIIL notifications@github.com:

**Comment by AlexIIL** [comment]
Well its more a mess of random ideas that may or may not be implemented.

**Comment by AlexIIL** [comment]
Some of them are more likely to be implemented than others though :)
