### ISSUE TITLE
When will a beta be releaseable?

### ISSUE THREAD

**Issue by asiekierka** [AlexIIL/Buildcraft_1.8_Issues#35]
Just curious.

(By the way, our old mc1.8 branch has block models for almost everything)

**Comment by AlexIIL** [comment]
Thats helpful. Except that blocks now have LED's and only 2 blocks need doing (the pump and the mining well). Gate static + dynamic rendering needs doing and facades need polishing. But there are basically no item models (which I don't think exist in the old mc1.8 branch)

**Comment by AlexIIL** [comment]
In terms of release dates, I'm not really sure. But I'm hoping before October. And it may be an alpha, as there are probably loads of horrible crash bugs caused by

**Comment by AlexIIL** [comment]
However so far most of the functionality of most blocks works so if you could ignore missing textures, missing item models etc you could probably play just fine.

**Comment by AlexIIL** [comment]
I say that, and then I try to use a filler and realise I must have broke it somewhere between now an 4 weeks ago :/

**Comment by AlexIIL** [comment]
Well, September has been and gone. If I ignore pipes for a week, I could have a beta of all the other modules (specifically core, builders, factory, energy and silicon) by then. Although I'm not sure about releasing buildcraft without pipes, as they kinda glue everything together nicely.

**Comment by iame6162013** [comment]
I think that would be a bad idea.

**Comment by AlexIIL** [comment]
@iame6162013 the more I think about it, the more I agree actually.

**Comment by asiekierka** [comment]
You could release it as an alpha so people can debug while you do the pipes.

2015-10-02 19:44 GMT+02:00 AlexIIL notifications@github.com:
