### ISSUE TITLE
Remove diamond kinesis pipes.

### ISSUE THREAD

**Issue by AlexIIL** [AlexIIL/Buildcraft_1.8_Issues#41]
And emerald kinesis pipes.
And golden kinesis pipes.

They just don't match up to the materials anymore, or make sense when changing kinesis pipes to be based purely around functionallity rather than power transfer. Also an alternative to the current iron valve kinesis pipes as they will be changed to be directional rather than actual valves (perhaps implemented with a seperate pluggable?

**Comment by iame6162013** [comment]
ohhh this could be nice :D

**Comment by AlexIIL** [comment]
I hope so too :D

**Comment by asiekierka** [comment]
They won't be changed to be directional in mainline BC yet, however it was being discussed for ages.

(Also, it only doesn't make sense in _your_ fork. Heh heh.)

**Comment by AlexIIL** [comment]
NOT APPLICABLE
