### ISSUE TITLE
Buff or remove Chutes

### ISSUE THREAD

**Issue by AlexIIL** [AlexIIL/Buildcraft_1.8_Issues#44]
Because they are terrible compared to item hoppers. Unless something interesting were to happen with them, I can't see a reason to keep them.

**Comment by asiekierka** [comment]
They're only in for historical reasons, and removing them would mean surrendering to Mojang.

Our answer was to lower their cost right now, but it is only a temporary measure.

(You should really ask these on the BC IRC or issue tracker instead. Haha.)

**Comment by AlexIIL** [comment]
NOT APPLICABLE
