### ISSUE TITLE
Add Andersite, Diortite and Granite pipes

### ISSUE THREAD

**Issue by AlexIIL** [AlexIIL/Buildcraft_1.8_Issues#45]
Which would do... I don't know yet. But its likely they wouldn't connect to stone, cobble or quartz unless anyone has any better ideas.

An alternative is to remove quartz from the disconnect mechanic, and make stone + cobble (and all the other pairs) not connect to any other pair, but instead the base variant (cobblestone + non-polished variants) act like normal, and the slightly upgraded variant (stone + polished variants) could act differently (Again, not sure how yet).

Possibilities include:
- Only connecting to the base variant but having a speed increase (same as gold pipes)
- (More TDB)

Quartz pipes would then have some alternative functionality (TBD)

Not sure if I should open a question on the forum for this, but I think I'll wait until BC is closer to a beta

**Comment by AlexIIL** [comment]
Implemented :)

**Comment by asiekierka** [comment]
More pipes!? We really don't need MORE pipes! We need less, if anything.
