### ISSUE TITLE
Update to latest BuildCraft

### ISSUE THREAD

**Issue by asiekierka** [AlexIIL/Buildcraft_1.8_Issues#46]
Proposed order:
- Finish your existing fork.
- Update to BuildCraft 7.0.12. (Any version between 7.0.12 and 7.0.17? should work fine, however.) Release. https://github.com/BuildCraft/BuildCraft/commit/43228d68528c736f7c0c08555be67633c1bb5a0c
- Start updating from that point by following the 7.1.x tree all the way to 7.1.8.
- Release.

The 6.5.x and 7.1.x tree after 7.0.12, and _especially_ after 7.0.19 contain a lot of duplicates.

**Comment by AlexIIL** [comment]
Thanks for the version numbers! Will do!

**Comment by asiekierka** [comment]
(If you want this to go a bit easier, make spaces tabs again. I still believe tabs are superior as you can configure them on your own IDE.)

**Comment by AlexIIL** [comment]
Oh, when I do this I will just reformat the 1.7.10 project to the same formatter I use for 1.8 and do a few other things (like changing imports from cpw.fml to net.minecraftfforge and enumdirection to enumfacing or enumpipepart) to make it easier.

Also does this mean we have started a holy war about spaces vs tabs?

**Comment by asiekierka** [comment]
Yes, yes it does mean exactly that.

(My idea was to merge the versions one by one and check if anything breaks. That way, you can do small incremental updates instead of one big swoop - which is probably a lot more motivating.)

**Comment by AlexIIL** [comment]
Huh. I hadn't thought of that. Good idea :)

**Comment by asiekierka** [comment]
I already tried porting 7.0.6 over, which is how I noticed.

2015-12-05 12:18 GMT+01:00 AlexIIL notifications@github.com:

**Comment by AlexIIL** [comment]
I JUST FOUND OUT GIT HAS "-Xignore-space-change".

OMFG THATS AMAZING

**Comment by AlexIIL** [comment]
(Just tried merging and found out I had huge differences, which was space changes)

**Comment by AlexIIL** [comment]
Wow, only 10k errors when merging directly from the 7.1.x branch? Esp. compared to the 30k I had when I wasn't using "-Xignore-space-change"

**Comment by AlexIIL** [comment]
The best part is that it was 10k errors 6 hours ago. During that time I've reduced it down to 8k errors :) (Oh, and had dinner and a bunch of ther stuff too)
