### ISSUE TITLE
Check for compat with this port of RF

### ISSUE THREAD

**Issue by AlexIIL** [AlexIIL/Buildcraft_1.8_Issues#47]
Vanhal/RedstoneFlux-API-1.8@69b50fdd55eb33ab52bf913e4fb0c6e046ccc075

**Comment by Xariyl** [comment]
I'm assuming the Progressive Automation mod is using the referenced API, since it is Vanhal's branch? 

Each of the PA Generators successfully send power through all versions of Kinesis pipes and can directly power BC machines (tested Refinery, Mining Well, and Quarry so far).

**Comment by AlexIIL** [comment]
Oh good :) Thanks for saying, I wasn't sure how I was going to test this originally
