### ISSUE TITLE
Crash when placing gate

### ISSUE THREAD

**Issue by Sp3rw3r** [AlexIIL/Buildcraft_1.8_Issues#49]
http://pastebin.com/zfgjKbHz

Occurs when a gate is placed. Tried basic and emerald gate. World crashes again after loading.

**Comment by AlexIIL** [comment]
Thanks. Building Alpha-3 now (just removing gate rendering completely, I will implement it properly later when I have more time)

**Comment by AlexIIL** [comment]
Alpha 2 has been removed and Alpha 3 is up that should fix the crash. (By not calling the render code for gates)

**Comment by AlexIIL** [comment]
Thanks for reporting this quickly :)

**Comment by Sp3rw3r** [comment]
Nice
Placing a docking station makes minecraft hang.
Might be related to same rendering issue.
But since it does not crash I don't have a report.

**Comment by AlexIIL** [comment]
Probably a completly separate issue then. I'll retest everthing today so hopefully there won't be any insta-crash bugs in alpha 4

**Comment by AlexIIL** [comment]
Huh. I couldn't recreate this issue in my dev environment...

**Comment by AlexIIL** [comment]
Ok, I'm closing this as docking stattions work fine for me in 7.2.0pre1
