### ISSUE TITLE
Builder crash when inserting "guildcastle2" blueprint

### ISSUE THREAD

**Issue by Sp3rw3r** [AlexIIL/Buildcraft_1.8_Issues#50]
I didn't have another mod independent blueprint. I try a normal one in a minute.
This one is extremely large and crashed with a ticking block entity:
 http://pastebin.com/95WhQEdN

**Comment by Sp3rw3r** [comment]
A small blueprint created with this mod worked without problems.

**Comment by AlexIIL** [comment]
Sorry for taking so long, I _think_ this has been fixed for alpha-4. I'll leave it open its released (spam me if it takes longer than monday) and you can confim if its fixed

**Comment by AlexIIL** [comment]
Would you look at that, its already Sunday and I haven't released alpha-4. Pushing it out now.

**Comment by AlexIIL** [comment]
This _should_ be fixed, but if it isn't feel free to re-open this :)
