### ISSUE TITLE
Crash after placing lasers (dedicated server)

### ISSUE THREAD

**Issue by maqjav** [AlexIIL/Buildcraft_1.8_Issues#54]
A new bug! http://pastebin.com/9UbKjYQm

I put an assembly table on the ground and on top of it 2 lasers (there is 2 empty blocks between the lasers and the assembly table, the lasers are attached to the ceiling of this little room), everything was working ok until I turned around and my server crashed (yes, I'm using a dedicated server for these tests)

EDIT: I've restarted the server and the lasers have disappeared (I want my diamonds back!).

**Comment by AlexIIL** [comment]
Looks like I am using a client side only method somewhere. Thanks!

**Comment by AlexIIL** [comment]
Wait, You can only subtract block positions on the client? whaaaaaat?

**Comment by AlexIIL** [comment]
Fixed for alpha 8. (Don't close it until it WORKS on alpha 8 though)

**Comment by AlexIIL** [comment]
You lost your diamonds? :(

**Comment by maqjav** [comment]
Hehe, it's ok, It is the price to pay for finding a bug.
I will let you know if I can reproduce it again with alpha 8.

**Comment by maqjav** [comment]
With the last alpha 0.8 this error is fixed, however I found some new (or better said, bugs I couldn't find before because it wasn't working).

If you prefere we can close this issue and open a new one, just let me know.
1. If you attach a combustion engine to a laser (with some kinetic iron pipes) there is no energy going on, or at least you can't see the "electricity" in the pipe (perhaps the energy is only produced if the laser is actually crafting something on an assembly table?)
2. Imagining that the laser has energy with the previous setup, if you put an assembly table beside and add redstone, iron bars and red ink, it will give you 3 possible items to craft. I clicked on the red wires and after that it didn't let me select other items. After some seconds I got this crash: http://pastebin.com/9yeZw4x1
3. Just a silly thing. If you destroy the laser the particles that appear when you hit it with a pick are purple and black (same colours as the blocks without textures or broken textures).

**Comment by AlexIIL** [comment]
1) I'm going to have to look into that further 
2) looks like I'm calling a client side only function on the dedicated server
3) 1 line change in the block model file to fix :)

**Comment by maqjav** [comment]
That sounds easy!
I connected the same engine to a quarry instead and it worked just fine, so it clearly looks an issue with the laser.
As soon as the texture is 100% correct I will update the other thread checking the lasers..

It would be great if you can fix the model of the assembly table too, so I can test the whole assembly process with the proper textures.

**Comment by AlexIIL** [comment]
Ok, after looking at (2) I cannot reproduce it- however that could just be because I accidentally fixed it between 0.8 and my dev environment (I tested on a dedicated server). Looks like 0.9 will be 3 of December rather than today as well.

**Comment by AlexIIL** [comment]
LOOKING AT IT AGAIN I think its because I forgot how everything obfuscates. woops.

**Comment by AlexIIL** [comment]
k, I THINK this has been fixed for alpha 9

**Comment by maqjav** [comment]
Ok, here are some fresh news!
1. Solved, although there is a tiny little visual bug. If you have 1 energy source connected to a kinetic pipe, and from this pipe you connect 2 pipes (looking like a T) and from each pipe 1 laser, I can see the energy going to only one of the lasers. Both lasers work (you can see the multicolour beams comming from them), but one of the pipes connected to one of the lasers is empty.
2. No crash at all!, let's craft gates!
3. I'm still seeing the purple and black particles (I know... this is so silly, but... you know...)

**Comment by AlexIIL** [comment]
1) dammit! That's a bit annoying...
2) yay :)
3) Looks like I missed that... But I have done it now so it will be in alpha 10

**Comment by maqjav** [comment]
Yay!, no more purple particules with alpha 10 :+1: 

Wait a second!, did you fix the visual issue already? now I'm seeing energy in both lasers pipes. 
EDIT: Umm, it seems that if you restart the server it actually works, however, if I break the pipe and re-attach it, then it doesn't.

**Comment by maqjav** [comment]
All the issues were solved a long time ago with the last pre releases.
