### ISSUE TITLE
You can place 2 gates in same spot

### ISSUE THREAD

**Issue by maqjav** [AlexIIL/Buildcraft_1.8_Issues#56]
If you place an iron gate on a pipe (1 block length), and then you place another iron gate on the same pipe, both gates are attached. When you click right on the gates you access to only one of them.
If you break the block, both gates are recovered.

I tested with an iron gate, but it might happend with every gate.

**Comment by AlexIIL** [comment]
Hang on, WHAT?

**Comment by AlexIIL** [comment]
Thats not happening for me...

**Comment by AlexIIL** [comment]
Oh, and you can place 6 gates on a single pipe (max 1 per side). Are you saying that it is possible to place 2 gates on the same side of a pipe?

**Comment by maqjav** [comment]
Oook, nevermind! I didn't know that, I thought you could add only 1 gate per chunk of pipe, not per side. I tried adding another gate in the same side where I had one gate and it's not possible, it opens the GUI of the gate 

Closing right away!

**Comment by AlexIIL** [comment]
Yeah, its been like that since BC 7 I think. Although without models it was probably hard to tell :)
