### ISSUE TITLE
Missing label name for engine GUI

### ISSUE THREAD

**Issue by maqjav** [AlexIIL/Buildcraft_1.8_Issues#57]
Same problem with stirling engines and combustion engines.

When you open the GUI you can read in the middle of the screen:
- "tile.engineStone.name" for Stirling engines.
- "tile.engineIron.name" for Combustion engines.

**Comment by Xariyl** [comment]
Fixed in buildcraft-7.2.0pre4. Respective engine names are displaying properly in GUI.
