### ISSUE TITLE
Extraction pipes do not automatically connect to tank or inventory sides

### ISSUE THREAD

**Issue by Xariyl** [AlexIIL/Buildcraft_1.8_Issues#58]
Not sure if this is intended or not? Wooden Fluid Pipes and Emerald Fluid pipes seem to not automatically see the sides of the BC tanks as a valid output when first placed, and fluid cannot be pumped out. However you can shift+RightClick with a wrench to get the pipes to attach and fluid will then flow.

They _do_ connect automatically when placed at the top or bottom of the tank.

using version buildcraft-0.9-alpha

**Comment by AlexIIL** [comment]
Not intended, thanks

**Comment by AlexIIL** [comment]
OOh, sneaky version number addition :P 
Please don't do that as github won't email me with the new comment (Unless I can change that In the options somewhere?)

**Comment by Xariyl** [comment]
After I commented, realized I should let you know what I was actually using at the time; you replied as I was editing :)

**Comment by AlexIIL** [comment]
:P

**Comment by Xariyl** [comment]
Updated title and confirmed that it's true with all inventories, item and fluid extraction pipes.

**Comment by AlexIIL** [comment]
This should have been fixed in my massive port. But the beta for it is not coming out very close to now, so ignore this if you don't work on BuildCraft :)

**Comment by AlexIIL** [comment]
This might be fixed in 7.2.0pre1

**Comment by AlexIIL** [comment]
This should now be fixed in pre2

**Comment by Xariyl** [comment]
Confirmed fixed as of buildcraft-7.2.0pre4. Thanks.
