### ISSUE TITLE
Crashes in Debug World

### ISSUE THREAD

**Issue by williewillus** [AlexIIL/Buildcraft_1.8_Issues#60]
In the new 1.8+ [debug world type](http://minecraft.gamepedia.com/Debug_mode) added by Mojang, BuildCraft TE's repeatedly try to run their logic and crash (this also seems like a mojang design issue so I will report it to them as well).

I like using this world type because it generates a flat plane with all possible blocks and all combinations of their listed property states, which allows us to make sure models are correctly provided.

Thanks!

**Comment by AlexIIL** [comment]
Fortunately its an easy fix: Just checking if its a debug world, and not running ANYTHING if it is. Unfortunately it has to be added everywhere :/

**Comment by AlexIIL** [comment]
Hang on, I've just made one and I don't crash at all... hopefully that means that this bug will fix itself for 7.2.0.

**Comment by Xariyl** [comment]
No crash with 7.2.0pre4.
