### ISSUE TITLE
Kinesis pipe Energy render irregularities 

### ISSUE THREAD

**Issue by LuigiHutch** [AlexIIL/Buildcraft_1.8_Issues#62]
Buildcraft 7.2.0 Prerelease 1

Extraction kinesis pipes render power oddly. See Image:
![2015-12-17_22 27 22](https://cloud.githubusercontent.com/assets/9326429/11883905/ee370e0a-a50d-11e5-86ec-66bf3d2a0fe2.png)

Also, do you plan to readd the Singleplayer rendering optimization that is showcased here: 
https://www.youtube.com/watch?v=RQ8Db_RuLpU&index=20&list=LLMvbw4y440gSuuURmWLujVg

 -LuigiHutch

**Comment by AlexIIL** [comment]
I'm dumb. What exactly is wrong here?

**Comment by LuigiHutch** [comment]
The power should be the same the whole way through the pipes iirc. There should be no sharp cut off like that.

**Comment by AlexIIL** [comment]
Oh. That's going to be difficult to fix.

**Comment by Xariyl** [comment]
Can you confirm that power is actually being cut off? I had always taken it as an intentional graphical display. The wooden kinesis pipes carry less power than the gold pipe, so the "percentage" of the pipe used _appears_ to be less in the gold.

**Comment by LuigiHutch** [comment]
Well, in BC 7.1 and below the size of the beam in the pipe was always the same no matter what pipe it was in so I assumed it was supposed to be the same.

If not supposed to be the same, it still looks odd so making the transition smoother would be cool :)

**Comment by Xariyl** [comment]
Actually I think you might be right, Luigi. Look at the pipes in F3 mode. I strung a wooden, 2 gold, and 2 diamond kinesis pipes to a quarry, and set the admin engine to output 320 RF/t. The wooden pipe filled completely with the power beam (maxed out, as expected). But in F3, the tooltip showed East and West flows at 64 RF. The 2 gold pipes, as in your images, showed a decreased beam size and showed East and West flows at 22RF. The two Diamond pipes showed an even further decrease in beam size, with East and West flows at 11RF. Using a stirling engine shows values of 8, 3, and 1 respectively.

Assuming I'm reading the F3 screen correctly. The Debug tool does not seem to work in this version.

The quarry is only 6 blocks away from the engine, and I do not have the power-loss-over-distance value turned on.

Using buildcraft-7.2.0pre1.

**Comment by AlexIIL** [comment]
The debug values are not representative of the actual RF values- they are actually the values sent to the client by the server, telling the client how wide it should be. I should probably remove the "RF" part to avoid confusion

**Comment by AlexIIL** [comment]
Also I might be removing the debug tool as its not as helpful as just using the debug screen to debug

**Comment by Xariyl** [comment]
Okay. Without seeing actual numbers, then, I'm going to assume it's just graphical. I put 5 wooden pipes around a single gold with creative engines at 320 RF/t. While not enough to max out a gold pipe, the power beam in the gold and the diamond pipes were significantly thicker, implying the increased throughput.

**Comment by LuigiHutch** [comment]
The reason that the pipe information had to be obtained by the debugger is to make numbers less of an importance and to give a more immersive experience for they user.

The numbers being in the f3 screen may may people think that BC is just a numbers game which IMO is not good from a gameplay standpoint. I think the debugger should stay

**Comment by AlexIIL** [comment]
Perhaps I will disable F3 (menu) unless the player is in creative mode. Also its not too much of a problem to fix, I just need to divide the RF in a pipe by the maximum of ANY pipe rather than that specific pipe.

**Comment by Xariyl** [comment]
> Also its not too much of a problem to fix, I just need to divide the RF in a pipe by the maximum of ANY pipe rather than that specific pipe.

For what it's worth, I kind of like it as is... visual efficiency check :)

**Comment by AlexIIL** [comment]
Fixed for pre9.

**Comment by LuigiHutch** [comment]
Fixed in Pre-9 :D
