### ISSUE TITLE
BC Gui's display MJ in tab

### ISSUE THREAD

**Issue by LuigiHutch** [AlexIIL/Buildcraft_1.8_Issues#66]
Buildcraft 7.2.0 Prerelease 1

In the GUI ledgers, is displays the numbers in MJ. The problem with this is that in the original Mj it was 1MJ to 10RF. This may cause confusion as the differant MJ's use differant values so new users may get confused as many old BC wiki's still display that BC has MJ so this can be very confusing to new users.

-LuigiHutch

**Comment by AlexIIL** [comment]
Thats a bug. MJ is dead.

**Comment by LuigiHutch** [comment]
Oh, okay :)

**Comment by AlexIIL** [comment]
Can you screenshot all of GUI's that have this? I can't seem to find any :/

**Comment by LuigiHutch** [comment]
Not a GUI But:
![2015-12-20_17 47 47](https://cloud.githubusercontent.com/assets/9326429/11919186/2d89a8d8-a743-11e5-8a07-a8f13d32ba24.png)

Sorry, My mistake

 -LuigiHutch

**Comment by AlexIIL** [comment]
oh, ok. Thanks :)
