### ISSUE TITLE
Quarry's digging arm turns invisible after a while...

### ISSUE THREAD

**Issue by Xariyl** [AlexIIL/Buildcraft_1.8_Issues#67]
After a few minutes of letting the quarry run, I noticed that the vertical digging-arm -- sorry, can't remember what it's properly called -- seemed to go invisible. It's still mining, however, blocks are piped out as expected.

[Screenshot](http://i.imgur.com/Z1LfcHY.png)

**Comment by AlexIIL** [comment]
Oh. Thats cause by an incorrect bounding box (I think). Try flying down to the bottom of the quarry?

**Comment by Xariyl** [comment]
I was incorrect... it depends on what angle I'm viewing from. When I'm on level ground with the bottom of the frame, the digging-arm is invisible. When I creative-fly above it slightly, the arm is visible again.

**Comment by AlexIIL** [comment]
That timing :P

**Comment by Xariyl** [comment]
:-)

**Comment by AlexIIL** [comment]
SO I thought I had fixed this but I had only fixed it for TESR's, but it turns out that entities are only rendered if you can see the minichunk (16_16_16) that they are in. Looks like I am going to have to render them slightly differently then

**Comment by AlexIIL** [comment]
Fixed for pre3

**Comment by Xariyl** [comment]
Confirmed, fixed!
