### ISSUE TITLE
Crash with Emerald Extraction pipe changing modes

### ISSUE THREAD

**Issue by Xariyl** [AlexIIL/Buildcraft_1.8_Issues#70]
When changing an Emerald Extraction pipe to either Blacklist or Round-Robin modes, my client crashes.

[Crash log](https://gist.github.com/Xariyl/45dc72ac5aac30382bce)

**Comment by Xariyl** [comment]
Same crash with Emzuli pipe, when changing any settings.

**Comment by AlexIIL** [comment]
This should now be fixed in pre2

**Comment by Xariyl** [comment]
Confirmed fixed using buildcraft-7.2.0pre4.

(p.s.: What's the protocol? Should I close the issue, or let you do it?)

**Comment by AlexIIL** [comment]
Ah sorry for not getting back to you: I was thinking of letting you close issues after you can confirm that the problem you had is fixed. This was I don't prematurely close an issue just because I no longer noticed it, as I may have missed something :)

**Comment by AlexIIL** [comment]
I might have missed some of the other issues for you to close but I'm sure I will find them in the future :)
