### ISSUE TITLE
Placing levers on facades

### ISSUE THREAD

**Issue by univrsal** [AlexIIL/Buildcraft_1.8_Issues#71]
Placing a facade on a pipe allows me to place a lever or button only on the opposite site.
Torches work just fine, and redstone torches just fall off.

Versions:
Forge: 11.15.0.1635
Buildcraft: 7.2.0-alpha

![bc-issue](https://cloud.githubusercontent.com/assets/8353672/11897282/b26ddf08-a58e-11e5-816c-e394b058a88b.png)

**Comment by AlexIIL** [comment]
I think that's a forge bug? Try without BuildCraft installed with the back of stairs?

**Comment by AlexIIL** [comment]
This looks like its related to MinecraftForge/MinecraftForge/issues/2204

**Comment by AlexIIL** [comment]
Forge fixed this in MinecraftForge/MinecraftForge@d2248c3774713bb0f5931504ceb2382e41566c62
