### ISSUE TITLE
Gates dont update until it recieves a block update

### ISSUE THREAD

**Issue by LuigiHutch** [AlexIIL/Buildcraft_1.8_Issues#73]
BuildCraft 7.2.0 prerelease 4 for minecraft 1.8.8

Gates dont update until it recieves a block update. See images:

![2015-12-20_18 03 13](https://cloud.githubusercontent.com/assets/9326429/11919214/1eca2718-a744-11e5-8e1e-4714435fa009.png)
![2015-12-20_18 03 16](https://cloud.githubusercontent.com/assets/9326429/11919213/1ec83994-a744-11e5-885c-ec1791de0f70.png)
![2015-12-20_18 03 21](https://cloud.githubusercontent.com/assets/9326429/11919212/1ec7516e-a744-11e5-9b94-4b88cab1286d.png)

Thanks
 -LuigiHutch

**Comment by AlexIIL** [comment]
This should be fixed in pre10 now.
