### ISSUE TITLE
Crash when breaking block without breaking particle icon with a filler (probably a builder too)

### ISSUE THREAD

**Issue by primetoxinz** [AlexIIL/Buildcraft_1.8_Issues#75]
http://paste.ee/p/cW89A

To reproduce, remove a chest with a filler

**Comment by AlexIIL** [comment]
I cannot reproduce this in my dev environment with a chest. Can you update to pre4 (it came out very quickly afterwards, I won't make that mistake in the future) and see if it happens?

**Comment by primetoxinz** [comment]
I can no longer reproduce it with chests on pre4, but blocks from Chisels And Bits crash the same way

**Comment by AlexIIL** [comment]
Can you reproduce this with JUST BuildCraft pre1 and a chest? Because I am starting to think that this isn't BuildCraft's issue

**Comment by AlexIIL** [comment]
I'm closing this for now but re-open if you can reproduce this is ONLY buildcraft
