### ISSUE TITLE
Sponge incompatibility

### ISSUE THREAD

**Issue by AlexIIL** [AlexIIL/Buildcraft_1.8_Issues#78]
Reopening https://github.com/BuildCraft/BuildCraft/issues/3167 in the proper repository :)

**Comment by AlexIIL** [comment]
Also https://github.com/SpongePowered/SpongeForge/issues/457

**Comment by AEnterprise** [comment]
wouldn't it be better to keep those reports in the BC issue tracker? just use a label for teh 1.8 issues?

**Comment by AlexIIL** [comment]
Yeah I'm starting to think so... especially because people are downloading 1.8.8 without reading where I want issues to be reported and jumping to the official repo

**Comment by AEnterprise** [comment]
yeah, currently there are 3 locations for bug reports, the forums, here and people are using the official BC repo, better to reduce it to 2 or even 1 (put the forum reports on the issue tracker as well) or bugs might be overlooked and forgotten
