### ISSUE TITLE
Crash with mining well - java.lang.ArrayIndexOutOfBoundsException: 16 	at net.minecraft.block.Block.getHarvestTool(Block.java:2021)

### ISSUE THREAD

**Issue by BBoldt** [AlexIIL/Buildcraft_1.8_Issues#79]
https://gist.github.com/9fb461c5da22c91e6e62

**Comment by BBoldt** [comment]
Again, with the quarry. I watched it this time, it was mining a piece of stone.

https://gist.github.com/b69dcc28dee780552997

**Comment by AlexIIL** [comment]
Looks like this is an issue with a different mod- try removing mods one by one until it no longer happens and report it to them :)

**Comment by BBoldt** [comment]
Yeah, I meant to close this after what Boni told me about it.

I'll comment on what caused it here when I find out though, in case someone stumbles upon this issue in the future.

**Comment by AlexIIL** [comment]
Thanks :)
