### ISSUE TITLE
Crash activating builder

### ISSUE THREAD

**Issue by Xariyl** [AlexIIL/Buildcraft_1.8_Issues#81]
When sending RF to a Builder that has a Blueprint, I get [this crash](https://gist.github.com/Xariyl/109cbbcc8f7a7627f260). After crash I can log back into the world; if I try to re-place the blueprint (thus re-activate the Builder) while it still has RF, the crash reoccurs.

Tested in Creative, using buildcraft-7.2.0pre4.

**Comment by AlexIIL** [comment]
I guess that only happens with older blueprints though as I couldn't reproduce in my test world. However its possible for that to be null so that _should_ have fixed it.

**Comment by Xariyl** [comment]
Good point, it was using an older blueprint. I'll test tomorrow with one built in the current version.

**Comment by AlexIIL** [comment]
I still need compatibility with older blueprints, that was just my excuse for not finding it earlier :)
