### ISSUE TITLE
Items are not properly saved in blueprints

### ISSUE THREAD

**Issue by AlexIIL** [AlexIIL/Buildcraft_1.8_Issues#87]
Mostly caused by items being saved with text ID's rather than integer ID's. Also this isn't so much of a problem in pre5 as it is in dev atm so no-one else knows about this.

**Comment by AlexIIL** [comment]
... And you fixed it. GO on, pat yourself on the back. For a bug no-one else experienced. _claps_

**Comment by Xariyl** [comment]
:clap:

:smile:
