### ISSUE TITLE
Zone Planner doesn't render the map in-world

### ISSUE THREAD

**Issue by LuigiHutch** [AlexIIL/Buildcraft_1.8_Issues#90]
Forge 11.15.0.1688
BC 7.2.0 Pre 5

The Zone Planner doesn't show the World in the GUI:
![2016-01-11_21 39 02](https://cloud.githubusercontent.com/assets/9326429/12247685/09840e30-b8ad-11e5-8929-a5aa4ae4f571.png)

Paint Brushes go dark when hover overing them from right to left
![2016-01-11_21 39 40](https://cloud.githubusercontent.com/assets/9326429/12247687/0bc98454-b8ad-11e5-9ba8-a69b7c012a0b.png)

The Zone Panner does not show the world on its exterior:
![2016-01-11_21 39 09](https://cloud.githubusercontent.com/assets/9326429/12247689/0db09a78-b8ad-11e5-8594-62b5d01d16a5.png)

**Comment by LuigiHutch** [comment]
Actually I have BC 7.2.0 pre 6. The ingame modlist lied to me :/

**Comment by LuigiHutch** [comment]
Map in the GUI fixed, Closing for now :)

**Comment by AlexIIL** [comment]
Not fixed yet :P

**Comment by LuigiHutch** [comment]
I was going to move the inworld map issue to the main repo, sorry for the confusion :)

**Comment by AlexIIL** [comment]
aaaah thats fine then
