### ISSUE TITLE
Floodgate Texture + Wrenching a Floodgate Crash

### ISSUE THREAD

**Issue by LuigiHutch** [AlexIIL/Buildcraft_1.8_Issues#94]
Forge 11.15.0.1688
BC 7.2.0 Pre 6

When creating a floodgate it looks like this (1.8):
![2016-01-14_16 30 36](https://cloud.githubusercontent.com/assets/9326429/12330359/9bbb391e-badc-11e5-9e97-a9687f0922d6.png)

When instead it is supposed to look like this (1.7):
![2016-01-14_16 36 39](https://cloud.githubusercontent.com/assets/9326429/12330431/03caf760-badd-11e5-9819-892ab0b80a79.png)

When attempting to wrench the floodgate to make it look how it is supposed to be, I recieved this crash:
https://gist.github.com/LuigiHutch/65df9f4442abf0330b06

**Comment by AlexIIL** [comment]
Oh right... I didn't give the floodgate any state information, and just assumed I had got the sides correct :P

**Comment by LuigiHutch** [comment]
Doesn't Crash anymore, Moving to Main Repo :)
