### ISSUE TITLE
Weird Crash

### ISSUE THREAD

**Issue by jubalearly** [AlexIIL/Buildcraft_1.8_Issues#97]
I made a stack of gold pipes inside a tinker's crafting table.  I then placed half the stack back into the same crafting table intending to add redstone and turn them into kintetic pipes.  This crashed the game and I can no longer load this save file.  Here is the crash report.

I should add I have been using tinkers crafting tables without incident in this game.  

[crash-2016-01-15_22.41.40-client.txt](https://github.com/AlexIIL/Buildcraft_1.8_Issues/files/93027/crash-2016-01-15_22.41.40-client.txt)

**Comment by AEnterprise** [comment]
the tinkers table tries to render the items it contains on top of the table and that crashes, i think tinkers has a config for this, if you dissable that you should be able to re-enter your world

**Comment by jubalearly** [comment]
Updated to latest tinkers (the one from FTB Unstable) and was able to enter world. Sorry to waste your time.
